# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b93dda13-4754-4140-9dfd-45a44c901317";
      fsType = "ext4";
    };

  fileSystems."/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/e596914c-ab40-4fc7-85b6-70fe46b89dbb";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker/devicemapper" =
    { device = "/var/lib/docker/devicemapper";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/docker/devicemapper/mnt/e2931c9e9336012d5f3c40650cef513173fdb7d087b73e5d9162b5747503ebe8" =
    { device = "/dev/disk/by-uuid/6d228163-3c10-425a-b524-1764f6579e72";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker/containers/f1723efefe029f615eb045d69b41c6379cbacb0fcaa0c40f37004ad9a66c2c6f/shm" =
    { device = "shm";
      fsType = "tmpfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
